export interface PaymentGateway{
    merchant_id: string, 
    return_url: string, 
    cancel_url: string, 
    notify_url: string, 
    first_name: string, 
    last_name: string, 
    email: string, 
    phone: string, 
    address: string, 
    city: string, 
    country: string, 
    order_id: string, 
    items: string, 
    currency: string, 
    amount: string, 
    hash: string,
    custom_1: boolean,
    custom_2: number
}